version: '3.8'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000"
    expose:
      - "5000" 

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        FLASK: flask-server
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt 
    depends_on:
      - flask-server
    ports:
      - "443:443"
    command: bash -c "nginx -g 'daemon off;'"
