version: '3.8'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    depends_on:
      - flask-server
    ports:
      - "443:443"
    command: bash -c "cron && nginx -g 'daemon off;'"
