version: '3.8'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
