version: '3.8'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000"
  nginx:
    image: nginx-latest
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-server
    ports:
      - "443:443"
