version: '3.8'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000"
    expose:
      - "5000" 

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    entrypoint: /renew_ssl.sh
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - flask-server
    ports:
      - "443:443"
    command: bash -c "nginx -g 'daemon off;'"
