version: '3.8'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    entrypoint: /renew_ssl.sh
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask-server
    ports:
      - "443:443"
    command: bash -c "nginx -g 'daemon off;'"
